name: Sync to Hugging Face hub
on:
  push:
    branches: [master]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: filter out images
        run: git filter-branch --force --index-filter "git rm --cached --ignore-unmatch *.png" --prune-empty --tag-name-filter cat -- --all
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push -f https://vicpada:$HF_TOKEN@huggingface.co/spaces/vicpada/superprofesApp master
        
      